stages:
    - test

variables:
    HOME: "/builds/abel0b"
    GIT_STRATEGY: none

test-arch:
    stage: test
    image: archlinux/base
    before_script:
        - pacman -Sy
        - pacman -S --noconfirm binutils
        - touch /etc/sudoers
    script:
        - curl https://raw.githubusercontent.com/abel0b/dotfiles/master/autosetup.sh | bash -

test-ubuntu:
    stage: test
    image: ubuntu
    before_script:
        - apt-get update -y
        - apt-get install -y curl
    script:
        - curl https://raw.githubusercontent.com/abel0b/dotfiles/master/autosetup.sh | bash -
