stages:
    - test

test-arch:
    stage: test
    image: archlinux/base
    before_script:
        - pacman -Sy
        - pacman -S --noconfirm binutils
        - touch /etc/sudoers
    script:
        - curl https://raw.githubusercontent.com/abel0b/dotfiles/master/autosetup.sh | bash -

test-ubuntu:
    stage: test
    image: ubuntu
    before_script:
        - apt-get update -y
    script:
        - curl https://raw.githubusercontent.com/abel0b/dotfiles/master/autosetup.sh | bash -
