stages:
    - test

test:
    stage: test
    image: archlinux/base
    before_script:
        - pacman -Sy
        - pacman -S --noconfirm binutils
        - touch /etc/sudoers
    script:
        - curl https://gitlab.com/abeliam/dotfiles/raw/master/setup.sh | bash -
