stages:
    - test

test:
    stage: test
    image: archlinux/base
    before_script:
        - pacman -Sy
        - pacman -S --noconfirm binutils
        - touch /etc/sudoers
    script:
        - curl https://raw.githubusercontent.com/abel0b/dotfiles/master/installer.sh | bash -

