#!/usr/bin/env bash

set -e

username=abel
shell=/usr/bin/bash
hostname=abelpc
local_domain=null
region=Europe
city=Paris
locale=en_US.UTF-8
keymap=fr

# Time zone
function time_zone {
    echo -e "\e[32m+\e[0m Time zone"
    ln -sf "/usr/share/zoneinfo/$region/$city" /etc/localtime
}

# Localization
function localization {
    echo -e "\e[32m+\e[0m Localization"
    sed -i "s/^#$locale/$locale/g" /etc/locale.gen
    locale-gen
    echo "LANG=$locale" > /etc/locale.conf
}

# Keyboard
function keyboard {
    echo -e "\e[32m+\e[0m Keyboard"
    echo "KEYMAP=$keymap" > /etc/vconsole.conf
}

# Network
function network {
    echo -e "\e[32m+\e[0m Network"
    echo "$hostname" > /etc/hostname
    echo "# Static table lookup for hostnames." > /etc/hosts
    echo "# See hosts(5) for details." >> /etc/hosts
    echo "127.0.0.1 localhost" >> /etc/hosts
    echo "::1		    localhost" >> /etc/hosts
    echo "127.0.1.1	$hostname.$local_domain" >> /etc/hosts
}

# Users
function users {
    sed -i "s/^# %wheel ALL=(ALL) ALL$/%wheel ALL=(ALL) ALL/" /etc/sudoers
    useradd -m -g users -G wheel -s $shell $username || true
}

# Softwares
function softwares {
    echo -e "\e[32m+\e[0m Softwares"
    pacman --sync --needed --noconfirm git

    cd $(mktemp -d)
    git clone https://aur.archlinux.org/package-query.git
    cd package-query
    makepkg -si
    cd ..
    git clone https://aur.archlinux.org/yaourt.git
    cd yaourt
    makepkg -si
    cd ..

    su -c "rm -rf ~/dotfiles && git clone https://gitlab.com/abeliam/dotfiles.git ~/dotfiles && cd ~/dotfiles && bash dotfiles install && bash dotfiles link" $username
}

if [ -z "$1" ]
then
    time_zone
    localization
    keyboard
    network
    users
    softwares
else
    $1
fi
