Install-PackageProvider –Name chocolatey
choco install -y vim
choco install -y notepadplusplus
choco install -y atom
choco install -y wsl
choco install -y wsl-ubuntu-1804
choco install -y vcxsrv
choco install -y gsudo
choco install -y docker
choco install -y fzf
choco install -y Firefox
choco install -y netcat
choco install -y nmap
choco install -y tmux
choco install -y ssh-copy-id
choco install -y gimp
choco install -y llvm
choco install -y obs-studio
choco install -y docker-cli
