# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Force la coloration du prompt (true/false)
COLOR_PROMPT="true"

# don't put duplicate lines or lines starting with space in the history
# avoid duplicates
HISTCONTROL=ignoreboth:erasedups

# append to the history file, don't overwrite it
shopt -s "histappend"

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE="1000"
HISTFILESIZE="2000"

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s "checkwinsize"

# if set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s "globstar"

# make less more friendly for non-text input files, see lesspipe(1)
[ -x "/usr/bin/lesspipe" ] && eval "$(SHELL=/bin/sh lesspipe)"

# enable color support of ls and also add handy aliases
if [ -x "/usr/bin/dircolors" ]; then
	[ -r "${HOME}/.dircolors" ] && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
	alias ls='ls --color=auto'
	alias grep='grep --color=auto'
fi

# some more ls aliases
alias l='ls -CF'
alias ll='ls -l'
alias la='ls -A'

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
	if [ -f "/usr/share/bash-completion/bash_completion" ]; then
		source "/usr/share/bash-completion/bash_completion"
	elif [ -f "/etc/bash_completion" ]; then
		source "/etc/bash_completion"
	fi
fi

# enable fzf bindings
if command -v fzf > /dev/null
then
    source /usr/share/doc/fzf/examples/completion.bash
    source /usr/share/doc/fzf/examples/key-bindings.bash
fi

export PS1='$(if [[ ! "$?" = "0" ]]; then echo "\[\e[1;31m\]($?)\[\e[0m\] "; fi)\h:\[\e[1;31m\]$(basename $PWD)\[\e[0m\]\[\e[1;33m\]$(__git_ps1 " [%s]")\[\e[0m\]> '

if command -v nvim > /dev/null
then
    alias vim='nvim'
    export EDITOR=nvim
elif command -v vim > /dev/null
then
    export EDITOR=vim
fi

# run x11 apps on windows subsystem linux
if grep -q Microsoft /proc/sys/kernel/osrelease
then
    export DISPLAY=localhost:0
fi

bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'

export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

function bashedit() {
	$EDITOR ~/.bashrc
}

function bashreload() {
	source ~/.bashrc
}

# use most as man pager
if command -v most > /dev/null
then
    export MANPAGER='most'
fi

export LESS_TERMCAP_mb=$(tput bold; tput setaf 2) # green
export LESS_TERMCAP_md=$(tput bold; tput setaf 6) # cyan
export LESS_TERMCAP_me=$(tput sgr0)
export LESS_TERMCAP_so=$(tput bold; tput setaf 3; tput setab 4) # yellow on blue
export LESS_TERMCAP_se=$(tput rmso; tput sgr0)
export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 7) # white
export LESS_TERMCAP_ue=$(tput rmul; tput sgr0)
export LESS_TERMCAP_mr=$(tput rev)
export LESS_TERMCAP_mh=$(tput dim)
export LESS_TERMCAP_ZN=$(tput ssubm)
export LESS_TERMCAP_ZV=$(tput rsubm)
export LESS_TERMCAP_ZO=$(tput ssupm)
export LESS_TERMCAP_ZW=$(tput rsupm)

if command -v fdfind > /dev/null
then
    alias fd='fdfind'
fi

alias goto='cd "$(fd -L . $(realpath ~/goto/*) | fzf)"'
PATH="$PATH:~/.local/bin"
